/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RideRouteImport } from './routes/ride'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SendRouteImport } from './routes/send'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TravelRouteImport } from './routes/travel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/cargo': typeof CargoRoute
  '/contact': typeof ContactRoute
  '/for-you': typeof ForYouRoute
  '/legal': typeof LegalRoute
  '/partners': typeof PartnersRoute
  '/ride': typeof RideRoute
  '/safety': typeof SafetyRoute
  '/send': typeof SendRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/cargo': typeof CargoRoute
  '/contact': typeof ContactRoute
  '/for-you': typeof ForYouRoute
  '/legal': typeof LegalRoute
  '/partners': typeof PartnersRoute
  '/ride': typeof RideRoute
  '/safety': typeof SafetyRoute
  '/send': typeof SendRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/cargo': typeof CargoRoute
  '/contact': typeof ContactRoute
  '/for-you': typeof ForYouRoute
  '/legal': typeof LegalRoute
  '/partners': typeof PartnersRoute
  '/ride': typeof RideRoute
  '/safety': typeof SafetyRoute
  '/send': typeof SendRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/travel': typeof TravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/cargo'
    | '/contact'
    | '/for-you'
    | '/legal'
    | '/partners'
    | '/ride'
    | '/safety'
    | '/send'
    | '/services'
    | '/shop'
    | '/support'
    | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/cargo'
    | '/contact'
    | '/for-you'
    | '/legal'
    | '/partners'
    | '/ride'
    | '/safety'
    | '/send'
    | '/services'
    | '/shop'
    | '/support'
    | '/travel'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business'
    | '/cargo'
    | '/contact'
    | '/for-you'
    | '/legal'
    | '/partners'
    | '/ride'
    | '/safety'
    | '/send'
    | '/services'
    | '/shop'
    | '/support'
    | '/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessRoute: typeof BusinessRoute
  CargoRoute: typeof CargoRoute
  ContactRoute: typeof ContactRoute
  ForYouRoute: typeof ForYouRoute
  LegalRoute: typeof LegalRoute
  PartnersRoute: typeof PartnersRoute
  RideRoute: typeof RideRoute
  SafetyRoute: typeof SafetyRoute
  SendRoute: typeof SendRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessRoute: BusinessRoute,
  CargoRoute: CargoRoute,
  ContactRoute: ContactRoute,
  ForYouRoute: ForYouRoute,
  LegalRoute: LegalRoute,
  PartnersRoute: PartnersRoute,
  RideRoute: RideRoute,
  SafetyRoute: SafetyRoute,
  SendRoute: SendRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
