import {
  AlertTriangle,
  BadgeCheck,
  CalendarClock,
  FileText,
  Gift,
  Layers,
  ListChecks,
  ShoppingBag,
  Banknote,
  Bike,
  Briefcase,
  Building2,
  Boxes,
  Car,
  Clock,
  CreditCard,
  Eye,
  Gauge,
  Handshake,
  HardHat,
  Headphones,
  Mail,
  MessageCircle,
  Map,
  MapPin,
  Network,
  Package,
  Route,
  Search,
  Shield,
  ShieldCheck,
  Sofa,
  Sparkles,
  Store,
  Truck,
  User,
  Warehouse,
  Wheat,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  car: Car,
  package: Package,
  truck: Truck,
  store: Store,
  shield: Shield,
  briefcase: Briefcase,
  route: Route,
  user: User,
  bike: Bike,
  handshake: Handshake,
  building: Building2,
  sparkles: Sparkles,
  eye: Eye,
  mail: Mail,
  whatsapp: MessageCircle,
  map: Map,
  "map-pin": MapPin,
  network: Network,
  "credit-card": CreditCard,
  "shield-check": ShieldCheck,
  gauge: Gauge,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  clock: Clock,
  headphones: Headphones,
  "calendar-clock": CalendarClock,
  layers: Layers,
  "list-checks": ListChecks,
  "file-text": FileText,
  gift: Gift,
  "shopping-bag": ShoppingBag,
  "alert-triangle": AlertTriangle,
  boxes: Boxes,
  "hard-hat": HardHat,
  wheat: Wheat,
  sofa: Sofa,
  search: Search,
  warehouse: Warehouse,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = map[name] ?? Sparkles;
  return <Cmp aria-hidden className={className} />;
}
